
# Site settings

url: "http://jnarvaezp.github.io"
baseurl: 
google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Jonathan Narvaez"
lang: "en"
title: "{ Jonathan Narvaez }"
favicon: "/img/favicon.ico"
description: "Website of Jonathan Narvaez"
keywords: "Jonathan, Narvaez, HPC, Telecomunications, Bioinformatics"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

#email: "correo@talvex.com"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/jnarvaezp"
  - title: "linkedin"
    url: "https://co.linkedin.com/in/jnarvaez"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables bellow this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
